// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID       int32
	Email    string
	Password string
}

type UserRole struct {
	UserID int32
	RoleID int32
}
